### ISSUE TITLE
Error while building the docker: FileNotFoundError during Shapely installation.

### ISSUE THREAD

**Issue by ibaris** [UMassMIRSL/isce_docker_tools#2]
After running the command 

```cmd
docker build -t isce_docker .
```
I run into the following error message:

```cmd
#5 211.1 Collecting shapely
#5 211.4   Downloading https://files.pythonhosted.org/packages/92/2e/a8bbe3c6b414c3c61c4b639ab16d5b1f9c4c4095817d417b503413e613c0/Shapely-1.8.5.post1.tar.gz (200kB)
#5 211.8     Complete output from command python setup.py egg_info:
#5 211.8     WARNING:/tmp/pip-build-5wnb3p7n/shapely/setup.py:Could not (re)create C extension with Cython.
#5 211.8     Traceback (most recent call last):
#5 211.8       File "<string>", line 1, in <module>
#5 211.8       File "/tmp/pip-build-5wnb3p7n/shapely/setup.py", line 342, in <module>
#5 211.8         subprocess.check_call(["cython", "shapely/speedups/_speedups.pyx"])
#5 211.8       File "/usr/lib/python3.6/subprocess.py", line 306, in check_call
#5 211.8         retcode = call(*popenargs, **kwargs)
#5 211.8       File "/usr/lib/python3.6/subprocess.py", line 287, in call
#5 211.8         with Popen(*popenargs, **kwargs) as p:
#5 211.8       File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
#5 211.8         restore_signals, start_new_session)
#5 211.8       File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
#5 211.8         raise child_exception_type(errno_num, err_msg, err_filename)
#5 211.8     FileNotFoundError: [Errno 2] No such file or directory: 'cython': 'cython'
#5 211.8
#5 211.8     ----------------------------------------
#5 211.8 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5wnb3p7n/shapely/
```

Maybe their is something wrong with the environment?

**Comment by shad0wcat** [comment]
I had the same issue. I had to mention the version of Shapely compatible with cython.  I changed the docker file to 

RUN pip3 install jinja2 requests boto3 lxml shapely==1.7.1 pandas utm 

and it worked
